language: java
jdk:
- oraclejdk7
script: ./travis_build.sh
env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: "IO4WVaFpFKWNFzPBZDko8kOwkYWeJP/rLDTN5vCvDwl9jmicSP81HEc635mXmsNMKLZpuk9Vw8uzd5OyXkMEOAZN6fc9iVNwDrsxzN0oSH3d/qpkN/vzoZyBMHya5v/j5pv6KOyXsocbQ53zpZK5jyEro9qfYo78+VqqgRaS+YQ="
  - secure: "S/p5l9hyW2E02VdDctU+bi+5BF3EzcNqL207dL7CaVmJ3j1yVj8CqxU3zFIF/LsPJDd16rDUTKBYobzyGOmWub5EbYFOqGFfLuRcc/3k4JdUfzxG+aydqDE5GFWi/WSNyModqGFi4KM1oJc6MkMxCUWwAruXbIloYPYPGLbMcO0="
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: repo.raymanoz.com
  region: eu-west-1
  endpoint: repo.raymanoz.com.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: target/s3
  upload-dir: com/unsprung/reloaded/reloaded_2.11/$BUILD_NUMBER
notifications:
  slack:
    secure: Jbs/sjJtMEKm6cg75s97mLJRM2ePm1cGVzqEAK+CWG4cdUsj0+BDwlUP+PX1HpTDH6VFOoNwECNJy3ZHU+7ljj/fTc3uOTTDaISSPp0LeUnTNDeZHijtZL8e9VWWJ+TR/2iQLzsmMW4AqR2qqcao0LhPPJCLajENkpLKrtva9EM=
